title: André Paul Grandsire
email: andre@startap.dev.br
description: ""
baseurl: "" # the subpath to our site
url: "https://andrepg.github.io" # main url of website @ github

# Social networks and where find me
social_media:
  instagram: anndrepaul
  github:  andrepg
  linkedin: andrepg
  freelancer: andrepaulg
  stackoverflow: 4252460

## Site settings - Analytics
google_analytics: UA-34405933-6
markdown: kramdown
rss: Feed RSS
timezone: America/Argentina/Buenos_Aires
date_format: "%d/%m/%Y"
destination: deployment
source: src
include: ['_pages']
exclude: ['*.backup']

# Build settings
theme: minima
plugins:
  - jekyll-target-blank

# Default settings for website
defaults:
