title: André Paul Grandsire
email: aplg.projetos@gmail.com
description: Um simples blog & cartão de visita
personal_description: >- # this means to ignore newlines until "baseurl:"
  <p>Comecei esse projeto para aprender algumas ferramentas úteis e acumular conhecimento.
  Esse site é construído em Jekyll, HTML, Sass & Markdown.</p>
  <p>Resolvi criar um blog com as experiências ao longo do tempo também. Mais uma vez.
  Dessa vez em Português, minha língua nativa.</p>
baseurl: "" # the subpath to our site
url: "https://andrepg.github.io" # main url of website @ github

# Social networks and where find me
social_media:
  twitter: anndrepaul
  github:  andrepg
  linkedin: andrepg
  freelancer: andrepaulg
  stackoverflow: 4252460

## Site settings - Analytics
google_analytics: UA-34405933-6
markdown: kramdown
rss: Feed RSS
timezone: America/Argentina/Buenos_Aires
date_format: "%d/%m/%Y"
destination: deployment
source: src
include: ['_pages']
exclude: ['*.backup']

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-target-blank
  - jekyll-paginate

# Default settings for website
defaults:
  - scope:
      path: ""
    values:
      layout: pages
  - scope:
      path: "_posts"
    values:
      layout: posts
      permalink: "/blog/:year/:month/:titlehtml"
  - scope:
      path: "_pages"
    values:
      permalink: '/pages/:basename'
